<div class="container">
    
    <div class="row">
        <div class="col-md-6">
            <h2 class="text-center">Festes</h2>
            <table class="table table-hover">
                <tr>
                    <th>Data</th>
                    <th>Participants</th>
                    <th>Apuntat</th>
                    <th>Detalls</th>
                </tr>
                <?php
                foreach ($this->festes as $f) {
                   
                    ?>
                <tr>
                <td><?php echo $f["data"] ?></td>
                <td><?php echo $f["participants"] ?></td>
                <td>
                    <a class="btn <?php echo $f["apuntat"]?"btn-danger":"btn-info"?>" href="<?php echo $this->url(array('controller'=>'index','action'=>'apuntar','id'=>$f["id"])) ?>"><?php echo $f["apuntat"]?"Desapuntar-se":"Apuntar-se" ?></a>
                </td>
                <td><a class="btn btn-info" href="<?php echo $this->url(array('controller'=>'index','action'=>'detalls','id'=>$f["id"])) ?>">Detalls</a></td>
                </tr>
                    <?php
                }
                ?>
            </table>
        </div>
        <div class="col-md-6">
            <h2 class="text-center">Festes pròpies</h2>
            <table class="table table-hover">
                <tr>
                    <th>Data</th>
                    <th>Participants</th>
                    <th>Detalls</th>
                </tr>
                <?php
                foreach ($this->festesPropies as $f) {
                    ?>
                <tr>
                <td><?php echo $f["data"] ?></td>
                <td><?php echo $f["participants"] ?></td>
                <td><a class="btn btn-info" href="<?php echo $this->url(array('controller'=>'index','action'=>'detalls','id'=>$f["id"])) ?>">Detalls</a></td>
                </tr>
                    <?php
                }
                ?>
                
            </table>
        </div>
    </div>
</div>