<form class="form-horizontal" name="f1" method="post" >
        <div class="form-group">
            <label for="email" class="control-label col-sm-2">Email:</label>
            <div class="col-sm-6">
                <input type="text" name="mail" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="pass" class="control-label col-sm-2">Contrasenya:</label>
            <div class="col-sm-6">
                <input type="password" name="pass" required="" class="form-control">
            </div>
        </div>
        <div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <input type="submit" name="enviar" value="Enviar" class="btn btn-primary">
                </div>
            </div>
        </div>
    </form>