<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Practica Zend</title>

        <link href="<?php echo $this->baseUrl() . "/recursos/css/bootstrap.min.css" ?>" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/recursos/css/font-awesome.min.css" ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/recursos/estil.css" ?>">
        <link href="<?php echo $this->baseUrl() . "/recursos/fileinput/css/fileinput.min.css" ?>" media="all" rel="stylesheet" type="text/css" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <!-- canvas-to-blob.min.js is only needed if you wish to resize images before upload.
             This must be loaded before fileinput.min.js -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/canvas-to-blob.min.js" ?>" type="text/javascript"></script>
        <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
             This must be loaded before fileinput.min.js -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/sortable.min.js" ?>" type="text/javascript"></script>
        <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
             This must be loaded before fileinput.min.js -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/purify.min.js" ?>" type="text/javascript"></script>
        <!-- the main fileinput plugin file -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/fileinput.min.js" ?>"></script>
        <!-- bootstrap.js below is needed if you wish to zoom and view file content 
             in a larger detailed modal dialog -->
        <!-- https://chmln.github.io/flatpickr/ -->

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
        <script src="https://unpkg.com/flatpickr"></script>
        <script src="https://npmcdn.com/flatpickr/dist/flatpickr.min.js"></script>
        <script src="https://npmcdn.com/flatpickr/dist/l10n/cat.js"></script>
        <style>
            .bootstrap-select {
                width: 100% !important;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Festes</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->baseUrl() . "/" ?>">Festes</a></li>
                        <li><a href="<?php echo $this->baseUrl() . "/index/crear" ?>">Crear festa</a></li>
                        <li><a href="<?php echo $this->baseUrl() . "/administrador" ?>">Administrar</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <?php echo $this->layout()->content; ?>
    </body>
    <script src="<?php echo $this->baseUrl() . "/recursos/js/bootstrap.min.js" ?>"></script>
</html>
