<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Practica Zend</title>
        
        <link href="<?php echo $this->baseUrl() . "/recursos/css/bootstrap.min.css" ?>" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/recursos/css/font-awesome.min.css" ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl() . "/recursos/estil.css" ?>">
    <link href="<?php echo $this->baseUrl() . "/recursos/fileinput/css/fileinput.min.css"?>" media="all" rel="stylesheet" type="text/css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- canvas-to-blob.min.js is only needed if you wish to resize images before upload.
         This must be loaded before fileinput.min.js -->
    <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/canvas-to-blob.min.js"?>" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
         This must be loaded before fileinput.min.js -->
    <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/sortable.min.js"?>" type="text/javascript"></script>
    <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
         This must be loaded before fileinput.min.js -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/plugins/purify.min.js"?>" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
        <script src="<?php echo $this->baseUrl() . "/recursos/fileinput/js/fileinput.min.js"?>"></script>
    <!-- bootstrap.js below is needed if you wish to zoom and view file content 
         in a larger detailed modal dialog -->
        
        <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
        <select class="selectpicker" data-live-search="true" multiple>
            <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
            <option data-tokens="mustard">Burger, Shake and a Smile</option>
            <option data-tokens="frosting">Sugar, Spice and all things nice</option>
        </select>
        <br><br>
        
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                </div>
            </div>
        </div>


            <label class="control-label">Select File</label>
    <input id="input-1" type="file" class="file" data-allowed-file-extensions='["csv"]' data-show-preview="false">
        
    </body>
        <script src="<?php echo $this->baseUrl() . "/recursos/js/bootstrap.min.js" ?>"></script>
</html>
